const exam_index = [
  {
    "folder_name": "📚 Subject Wise Tests",
    "exams": [
      { "name": "Digital Logic 1", "path": "Exams/000_PYQ/TEST_ID-23_[_DIGITAL_LOGIC-1]_-_2026..json" },
      { "name": "Digital Logic 2", "path": "Exams/000_PYQ/TEST_ID-24_[_DIGITAL_LOGIC-2]_-_2026.json" },
      { "name": "Digital Logic 3", "path": "Exams/000_PYQ/TEST_ID-25_[_DIGITAL_LOGIC-3]_-_2026.json" },
      { "name": "Digital Logic Full", "path": "Exams/000_PYQ/TEST_ID-26_[_DIGITAL_LOGIC_Full_]_-_2026.json" },
      { "name": "Math Test 1", "path": "Exams/000_PYQ/TEST_ID-41_[_MATH_Test_-1]-_2026.json" },
      { "name": "Math Test 2", "path": "Exams/000_PYQ/TEST_ID-42_[_MATH_Test_-2]-_2026.json" },
      { "name": "Math Test 3", "path": "Exams/000_PYQ/TEST_ID-43_[_MATH_Test_-3]-_2026.json" },
      { "name": "Math Test 4", "path": "Exams/000_PYQ/TEST_ID-44_[_MATH_Test_-4]-_2026.json" },
      { "name": "Math Full Test", "path": "Exams/000_PYQ/TEST_ID-45_[Math_Full]_2026.json" },
      { "name": "C-Programming Test 1", "path": "Exams/000_PYQ/TEST_ID-7_[C-Prog_Test_-1]_2026.json" },
      { "name": "C-Programming Full", "path": "Exams/000_PYQ/TEST_ID-8_[C-Prog_Full]_2026.json" },
      { "name": "DSA Test 1", "path": "Exams/000_PYQ/Test_ID_-_09_[DSA_Test_1]_2026.json" },
      { "name": "DSA Test 2", "path": "Exams/000_PYQ/Test_ID_-_10_[DSA_Test_2]_2026.json" },
      { "name": "DSA Test 3", "path": "Exams/000_PYQ/Test_ID_-_11_[DSA_Test_3]_2026.json" },
      { "name": "DSA Test 4", "path": "Exams/000_PYQ/Test_ID_-_12_[DSA_Test_4]_2026.json" },
      { "name": "DSA Full Test", "path": "Exams/000_PYQ/Test_ID_-_13_[DSA_Full_Test_]__2026.json" },
      { "name": "Computer Networks 1", "path": "Exams/000_PYQ/Test_ID_-_14_[CN_Test_-_1]_-_2026.json" },
      { "name": "Computer Networks 2", "path": "Exams/000_PYQ/Test_ID_-_15_[CN_Test_-_2]_-_2026.json" },
      { "name": "Computer Networks 3", "path": "Exams/000_PYQ/Test_ID_-_16_[CN_Test_-_3]_-_2026.json" },
      { "name": "Computer Networks 4", "path": "Exams/000_PYQ/Test_ID_-_17_[CN_Test_-_4]_-_2026.json" },
      { "name": "Computer Networks Full", "path": "Exams/000_PYQ/Test_ID_-_18_[CN_FULL_Test]_-_2026.json" },
      { "name": "Discrete Math 1", "path": "Exams/000_PYQ/Test_ID_-_1_[DM_Test_-_1]_-_2026.json" },
      { "name": "Discrete Math 2", "path": "Exams/000_PYQ/Test_ID_-_2_[DM_Test_-_2]_-_2026.json" },
      { "name": "Discrete Math 3", "path": "Exams/000_PYQ/Test_ID_-_3_[DM_Test_-_3]_-_2026.json" },
      { "name": "Discrete Math 4", "path": "Exams/000_PYQ/Test_ID_-_4_[DM_Test_-_4]_-_2026.json" },
      { "name": "Discrete Math 5", "path": "Exams/000_PYQ/Test_ID_-_5_[DM_Test_-_5]_-_2026.json" },
      { "name": "Discrete Math Full", "path": "Exams/000_PYQ/Test_ID_-_6_[DM_Test_full]_-_2026.json" },
      { "name": "COA Test 1", "path": "Exams/000_PYQ/Test_ID_-_27_[COA_Test_-1]_-_2026.json" },
      { "name": "COA Test 2", "path": "Exams/000_PYQ/Test_ID_-_28_[COA_Test_-2]_-_2026.json" },
      { "name": "COA Test 3", "path": "Exams/000_PYQ/Test_ID_-_29_[COA_Test_-3]_-_2026..json" },
      { "name": "COA Full Test", "path": "Exams/000_PYQ/Test_ID_-_30_[COA_FULL_Test]_-_2026.json" },
      { "name": "DBMS Test 1", "path": "Exams/000_PYQ/Test_ID_-_31_[DBMS_Test_-_1]_-_2026.json" },
      { "name": "DBMS Test 2", "path": "Exams/000_PYQ/Test_ID_-_32_[DBMS_Test_-_2]_-_2026.json" },
      { "name": "DBMS Test 3", "path": "Exams/000_PYQ/Test_ID_-_33_[DBMS_Test_-_3]_-_2026.json" },
      { "name": "DBMS Test 4", "path": "Exams/000_PYQ/Test_ID_-_34_[DBMS_Test_-_4]_-_2026.json" },
      { "name": "DBMS Full Test", "path": "Exams/000_PYQ/Test_ID_-_35_[DBMS_Test_-_Full]_-_2026.json" },
      { "name": "Compiler Design 1", "path": "Exams/000_PYQ/Test_ID_-_39_[Compiler_Test_1_-_]_2026.json" },
      { "name": "Compiler Design Full", "path": "Exams/000_PYQ/Test_ID_-_40_[Compiler_Full_Test_]_2026.json" },
      { "name": "Aptitude 1", "path": "Exams/000_PYQ/Test_ID_-_46_[Aptitude-1]_-_2026.json" },
      { "name": "Aptitude 2", "path": "Exams/000_PYQ/Test_ID_-_47_[Aptitude-2]_-_2026.json" },
      { "name": "Aptitude Full Test", "path": "Exams/000_PYQ/Test_ID_48_[Aptitude_Full_Test_]_-_2026.json" },
      { "name": "Operating System 1", "path": "Exams/000_PYQ/Test_ID_19_[OS_Test_1]_-_2026.json" },
      { "name": "Operating System 2", "path": "Exams/000_PYQ/Test_ID_20_[OS_Test_2]_-_2026.json" },
      { "name": "Operating System 3", "path": "Exams/000_PYQ/Test_ID_21_[OS_Test_3]_-_2026.json" },
      { "name": "Operating System Full", "path": "Exams/000_PYQ/Test_ID_22_[OS_Test_Full]_-_2026.json" },
      { "name": "TOC Test 1", "path": "Exams/000_PYQ/Test_ID_36_[TOC_Test_1]_-_2026.json" },
      { "name": "TOC Test 2", "path": "Exams/000_PYQ/Test_ID_37_[TOC_Test_2]_-_2026.json" },
      { "name": "TOC Full Test", "path": "Exams/000_PYQ/Test_ID_38_[TOC_Full_Test_]_-_2026.json" }
    ]
  },
  {
    "folder_name": "🔄 Round 1 (Revision)",
    "exams": [
      { "name": "Discrete Math", "path": "Exams/000_PYQ/Test_ID_-_49_[Round_-_1_DM_Test]_-_2026.json" },
      { "name": "Operating System", "path": "Exams/000_PYQ/Test_ID_-_50_[Round_-_1_OS_Test]_-_2026.json" },
      { "name": "Data Structures & Algo", "path": "Exams/000_PYQ/Test_ID_-_51_[Round_-_1_DSA_Test]_-_2026.json" },
      { "name": "Computer Networks", "path": "Exams/000_PYQ/Test_ID_-_52_[Round_-_1_CN_Test]_-_2026.json" },
      { "name": "Digital Logic", "path": "Exams/000_PYQ/Test_ID_-_53_[Round_-_1_Digital_Test]_-_2026.json" },
      { "name": "TOC", "path": "Exams/000_PYQ/Test_ID_54_[TOC_Round_01]_2026.json" },
      { "name": "COA", "path": "Exams/000_PYQ/Test_ID_-_55_[Round_-_1_COA_Test]_-_2026.json" },
      { "name": "Compiler + C-Prog", "path": "Exams/000_PYQ/Test_ID_-_56_[Round_-_1_Compiler_Design+C-Programming_Test_-_1]_-_2026.json" },
      { "name": "DBMS", "path": "Exams/000_PYQ/Test_ID_-_57_[Round_-_1_DBMS_Test]_-_2026.json" },
      { "name": "Engineering Math", "path": "Exams/000_PYQ/Test_ID_58_[Math's_Round_1]_2026.json" },
      { "name": "General Aptitude", "path": "Exams/000_PYQ/Test_ID_59_[Aptitude_Round_1]_-_2026.json" }
    ]
  },
  {
    "folder_name": "⚔️ Round 2 (Mixed Subjects)",
    "exams": [
      { "name": "Discrete + TOC + Compiler", "path": "Exams/000_PYQ/Test_ID_60_[Discrete_+TOC+_Compiler_Round_2-_2026].json" },
      { "name": "Digital Logic + COA", "path": "Exams/000_PYQ/Test_ID_61_-_[Round_2_DL_+_COA]_-_2026.json" },
      { "name": "Networks + DSA", "path": "Exams/000_PYQ/Test_ID_-_62_[Round_2_CN_+_DSA]_-_2026.json" },
      { "name": "OS + DBMS + C-Prog", "path": "Exams/000_PYQ/Test_ID_-_63_[Round_2_OS_+_DBMS_+_C_Prog]_-_2026.json" },
      { "name": "Maths + Aptitude", "path": "Exams/000_PYQ/Test_ID_64_[MAths_+_APT_Round_2]_2026.json" }
    ]
  },
  {
    "folder_name": "🎯 Full Length Mocks & AIMT",
    "exams": [
      { "name": "Mock Test 1", "path": "Exams/000_PYQ/Test_ID_-_65_[Mock_-_1]_-_2026.json" },
      { "name": "Mock Test 2", "path": "Exams/000_PYQ/Test_ID_-_66__[Mock_-_2]_-_2026.json" },
      { "name": "Mock Test 3", "path": "Exams/000_PYQ/Test_ID_-_67_[Mock_-_3]_-_2026.json" },
      { "name": "All India Mock Test (AIMT) 1", "path": "Exams/000_PYQ/Test_ID_-_68_[AIMT_-_1]_-_2026.json" },
      { "name": "Mock Test 4", "path": "Exams/000_PYQ/Test_ID_-_69_[Mock_-_4]_-_2026.json" },
      { "name": "Mock Test 5", "path": "Exams/000_PYQ/Test_ID_-_70_[Mock_-_5]_-_2026.json" },
      { "name": "Mock Test 6", "path": "Exams/000_PYQ/Test_ID_-_71__[Mock_-_6]_-_2026.json" },
      { "name": "All India Mock Test (AIMT) 2", "path": "Exams/000_PYQ/Test_ID_-_72_[AIMT_-_2]_-_2026.json" },
      { "name": "Mock Test 7", "path": "Exams/000_PYQ/Test_ID_-_73_[Mock_-_7]_-_2026.json" },
      { "name": "Mock Test 8", "path": "Exams/000_PYQ/Test_ID_-_74_[Mock_-_8]_-_2026.json" },
      { "name": "Mock Test 9", "path": "Exams/000_PYQ/Test_ID_-_75_[Mock_-_9]_-_2026.json" },
      { "name": "All India Mock Test (AIMT) 3", "path": "Exams/000_PYQ/Test_ID_-_76_[AIMT_-_3]_-_2026.json" },
      { "name": "Mock Test 10", "path": "Exams/000_PYQ/Test_ID_-_77__[Mock_-_10]_-_2026.json" },
      { "name": "Mock Test 11", "path": "Exams/000_PYQ/Test_ID_-_78_[Mock_-_11]_-_2026.json" },
      { "name": "Mock Test 12", "path": "Exams/000_PYQ/Test_ID_-_79_[Mock_-_12]_-_2026.json" },
      { "name": "All India Mock Test (AIMT) 4", "path": "Exams/000_PYQ/Test_ID_-_80_[AIMT_-_4]_-_2026.json" }
    ]
  }
];
